-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.cupboards
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text NOT NULL,
    type text NOT NULL,
    "user" text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.items
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text NOT NULL,
    barcode text,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 9223372036854775807 CACHE 1 ),
    password text NOT NULL,
    username text NOT NULL UNIQUE,
    email text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.cupboards_users
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 9223372036854775807 CACHE 1 ),
    cupboards_id bigint NOT NULL,
    users_id bigint NOT NULL,
    name text,
    PRIMARY KEY (id)
);

CREATE TABLE public.cupboards_items
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 9223372036854775807 CACHE 1 ),
    cupboards_id bigint NOT NULL,
    items_id bigint NOT NULL,
    expiry_date text,
    PRIMARY KEY (id)
);

ALTER TABLE public.cupboards_users
    ADD FOREIGN KEY (cupboards_id)
    REFERENCES public.cupboards (id)
    NOT VALID;


ALTER TABLE public.cupboards_users
    ADD FOREIGN KEY (users_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.cupboards_items
    ADD FOREIGN KEY (cupboards_id)
    REFERENCES public.cupboards (id)
    NOT VALID;


ALTER TABLE public.cupboards_items
    ADD FOREIGN KEY (items_id)
    REFERENCES public.items (id)
    NOT VALID;



END;