// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'MuiFormHelperText-root': string;
  'MuiFormLabel-root': string;
  'MuiInputLabel-root': string;
}
export const cssExports: CssExports;
export default cssExports;
